<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Book;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SMABooksSeederNew extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Book::truncate();
        Category::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Create Categories
        $categories = [
            ['name' => 'Matematika', 'description' => 'Buku paket mata pelajaran Matematika SMA'],
            ['name' => 'Bahasa Indonesia', 'description' => 'Buku paket mata pelajaran Bahasa Indonesia SMA'],
            ['name' => 'Bahasa Inggris', 'description' => 'Buku paket mata pelajaran Bahasa Inggris SMA'],
            ['name' => 'Fisika', 'description' => 'Buku paket mata pelajaran Fisika SMA'],
            ['name' => 'Kimia', 'description' => 'Buku paket mata pelajaran Kimia SMA'],
            ['name' => 'Biologi', 'description' => 'Buku paket mata pelajaran Biologi SMA'],
            ['name' => 'Sejarah', 'description' => 'Buku paket mata pelajaran Sejarah SMA'],
            ['name' => 'Geografi', 'description' => 'Buku paket mata pelajaran Geografi SMA'],
            ['name' => 'Ekonomi', 'description' => 'Buku paket mata pelajaran Ekonomi SMA'],
            ['name' => 'Sosiologi', 'description' => 'Buku paket mata pelajaran Sosiologi SMA'],
            ['name' => 'PPKn', 'description' => 'Buku paket mata pelajaran PPKn SMA'],
            ['name' => 'Seni Budaya', 'description' => 'Buku paket mata pelajaran Seni Budaya SMA'],
            ['name' => 'PJOK', 'description' => 'Buku paket mata pelajaran PJOK SMA'],
        ];

        foreach ($categories as $category) {
            Category::create($category);
        }

        // Create Books with complete data
        $books = [
            // KELAS X - Kurikulum Merdeka
            [
                'title' => 'Matematika untuk SMA/MA Kelas X',
                'subject' => 'Matematika',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-900-1',
                'description' => 'Buku paket Matematika untuk siswa kelas X SMA/MA. Membahas fungsi, trigonometri, dan statistika.',
                'published_date' => '2024-01-15',
                'pages' => 280,
                'language' => 'Indonesian',
                'stock' => 50,
                'price' => 85000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 1,
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subMonths(8)
            ],
            [
                'title' => 'Bahasa Indonesia untuk SMA/MA Kelas X',
                'subject' => 'Bahasa Indonesia',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-902-5',
                'description' => 'Buku paket Bahasa Indonesia untuk siswa kelas X SMA/MA. Membahas teks laporan, eksposisi, dan anekdot.',
                'published_date' => '2024-01-15',
                'pages' => 240,
                'language' => 'Indonesian',
                'stock' => 48,
                'price' => 78000,
                'condition' => 'baik',
                'damaged_count' => 2,
                'damage_notes' => 'Cover sobek pada 2 buku',
                'category_id' => 2,
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subMonths(2)
            ],
            [
                'title' => 'Bahasa Inggris untuk SMA/MA Kelas X',
                'subject' => 'Bahasa Inggris',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-903-2',
                'description' => 'English textbook for grade X students. Covers communication, descriptive texts, and conversations.',
                'published_date' => '2024-01-15',
                'pages' => 200,
                'language' => 'Indonesian',
                'stock' => 45,
                'price' => 72000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 3,
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(7)
            ],
            [
                'title' => 'Fisika untuk SMA/MA Kelas X',
                'subject' => 'Fisika',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-904-9',
                'description' => 'Buku paket Fisika untuk siswa kelas X SMA/MA. Membahas gerak, gaya, energi, dan momentum.',
                'published_date' => '2024-01-15',
                'pages' => 260,
                'language' => 'Indonesian',
                'stock' => 42,
                'price' => 82000,
                'condition' => 'baik',
                'damaged_count' => 3,
                'damage_notes' => 'Halaman lepas pada 3 buku',
                'category_id' => 4,
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(1)
            ],
            [
                'title' => 'Kimia untuk SMA/MA Kelas X',
                'subject' => 'Kimia',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-905-6',
                'description' => 'Buku paket Kimia untuk siswa kelas X SMA/MA. Membahas struktur atom, ikatan kimia, dan stoikiometri.',
                'published_date' => '2024-01-15',
                'pages' => 250,
                'language' => 'Indonesian',
                'stock' => 40,
                'price' => 80000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 5,
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(6)
            ],
            [
                'title' => 'Biologi untuk SMA/MA Kelas X',
                'subject' => 'Biologi',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-906-3',
                'description' => 'Buku paket Biologi untuk siswa kelas X SMA/MA. Membahas keanekaragaman hayati, virus, dan bakteri.',
                'published_date' => '2024-01-15',
                'pages' => 270,
                'language' => 'Indonesian',
                'stock' => 43,
                'price' => 81000,
                'condition' => 'baik',
                'damaged_count' => 1,
                'damage_notes' => 'Cover rusak 1 buku',
                'category_id' => 6,
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(3)
            ],
            [
                'title' => 'Sejarah Indonesia untuk SMA/MA Kelas X',
                'subject' => 'Sejarah',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-907-0',
                'description' => 'Buku paket Sejarah Indonesia untuk siswa kelas X SMA/MA. Membahas masa praaksara hingga kerajaan Hindu-Buddha.',
                'published_date' => '2024-01-15',
                'pages' => 220,
                'language' => 'Indonesian',
                'stock' => 46,
                'price' => 75000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 7,
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subMonths(5)
            ],
            [
                'title' => 'PPKn untuk SMA/MA Kelas X',
                'subject' => 'PPKn',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-930-8',
                'description' => 'Buku paket PPKn untuk siswa kelas X SMA/MA. Membahas nilai-nilai Pancasila dan sistem hukum Indonesia.',
                'published_date' => '2024-01-15',
                'pages' => 180,
                'language' => 'Indonesian',
                'stock' => 50,
                'price' => 70000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 11,
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subMonths(5)
            ],

            // KELAS XI - Kurikulum Merdeka
            [
                'title' => 'Matematika untuk SMA/MA Kelas XI',
                'subject' => 'Matematika',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-910-0',
                'description' => 'Buku paket Matematika untuk siswa kelas XI SMA/MA. Membahas limit, turunan, dan integral.',
                'published_date' => '2024-02-01',
                'pages' => 300,
                'language' => 'Indonesian',
                'stock' => 44,
                'price' => 88000,
                'condition' => 'baik',
                'damaged_count' => 1,
                'damage_notes' => 'Halaman robek 1 buku',
                'category_id' => 1,
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subMonths(1)
            ],
            [
                'title' => 'Bahasa Indonesia untuk SMA/MA Kelas XI',
                'subject' => 'Bahasa Indonesia',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-912-4',
                'description' => 'Buku paket Bahasa Indonesia untuk siswa kelas XI SMA/MA. Membahas teks prosedur, argumentasi, dan negosiasi.',
                'published_date' => '2024-02-01',
                'pages' => 250,
                'language' => 'Indonesian',
                'stock' => 42,
                'price' => 79000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 2,
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subMonths(4)
            ],
            [
                'title' => 'Fisika untuk SMA/MA Kelas XI',
                'subject' => 'Fisika',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-911-7',
                'description' => 'Buku paket Fisika untuk siswa kelas XI SMA/MA. Membahas gelombang, optik, dan listrik dinamis.',
                'published_date' => '2024-02-01',
                'pages' => 280,
                'language' => 'Indonesian',
                'stock' => 38,
                'price' => 85000,
                'condition' => 'rusak',
                'damaged_count' => 5,
                'damage_notes' => 'Banyak halaman lepas dan cover rusak',
                'category_id' => 4,
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subWeeks(2)
            ],
            [
                'title' => 'Kimia untuk SMA/MA Kelas XI',
                'subject' => 'Kimia',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-913-1',
                'description' => 'Buku paket Kimia untuk siswa kelas XI SMA/MA. Membahas termokimia, laju reaksi, dan kesetimbangan.',
                'published_date' => '2024-02-01',
                'pages' => 270,
                'language' => 'Indonesian',
                'stock' => 40,
                'price' => 83000,
                'condition' => 'baik',
                'damaged_count' => 2,
                'damage_notes' => 'Cover sobek 2 buku',
                'category_id' => 5,
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonths(1)
            ],
            [
                'title' => 'Biologi untuk SMA/MA Kelas XI',
                'subject' => 'Biologi',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-914-8',
                'description' => 'Buku paket Biologi untuk siswa kelas XI SMA/MA. Membahas sistem organ, genetika, dan evolusi.',
                'published_date' => '2024-02-01',
                'pages' => 290,
                'language' => 'Indonesian',
                'stock' => 41,
                'price' => 84000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 6,
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonths(3)
            ],
            [
                'title' => 'Ekonomi untuk SMA/MA Kelas XI',
                'subject' => 'Ekonomi',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-915-5',
                'description' => 'Buku paket Ekonomi untuk siswa kelas XI SMA/MA. Membahas ketenagakerjaan, pendapatan nasional, dan APBN.',
                'published_date' => '2024-02-01',
                'pages' => 240,
                'language' => 'Indonesian',
                'stock' => 39,
                'price' => 77000,
                'condition' => 'baik',
                'damaged_count' => 1,
                'damage_notes' => 'Halaman lepas 1 buku',
                'category_id' => 9,
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonths(2)
            ],

            // KELAS XII - Kurikulum Merdeka
            [
                'title' => 'Matematika untuk SMA/MA Kelas XII',
                'subject' => 'Matematika',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-920-9',
                'description' => 'Buku paket Matematika untuk siswa kelas XII SMA/MA. Membahas integral lanjut, statistika inferensial, dan matematika diskrit.',
                'published_date' => '2024-03-01',
                'pages' => 320,
                'language' => 'Indonesian',
                'stock' => 40,
                'price' => 90000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 1,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2)
            ],
            [
                'title' => 'Bahasa Indonesia untuk SMA/MA Kelas XII',
                'subject' => 'Bahasa Indonesia',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-922-3',
                'description' => 'Buku paket Bahasa Indonesia untuk siswa kelas XII SMA/MA. Membahas teks editorial, kritik, dan esai.',
                'published_date' => '2024-03-01',
                'pages' => 260,
                'language' => 'Indonesian',
                'stock' => 38,
                'price' => 80000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 2,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(2)
            ],
            [
                'title' => 'Fisika untuk SMA/MA Kelas XII',
                'subject' => 'Fisika',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-921-6',
                'description' => 'Buku paket Fisika untuk siswa kelas XII SMA/MA. Membahas fisika modern, radioaktivitas, dan teknologi digital.',
                'published_date' => '2024-03-01',
                'pages' => 300,
                'language' => 'Indonesian',
                'stock' => 35,
                'price' => 87000,
                'condition' => 'baik',
                'damaged_count' => 3,
                'damage_notes' => 'Cover rusak dan halaman lepas',
                'category_id' => 4,
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subWeeks(3)
            ],
            [
                'title' => 'Kimia untuk SMA/MA Kelas XII',
                'subject' => 'Kimia',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-923-0',
                'description' => 'Buku paket Kimia untuk siswa kelas XII SMA/MA. Membahas kimia organik, polimer, dan biokimia.',
                'published_date' => '2024-03-01',
                'pages' => 280,
                'language' => 'Indonesian',
                'stock' => 37,
                'price' => 85000,
                'condition' => 'baik',
                'damaged_count' => 1,
                'damage_notes' => 'Halaman robek 1 buku',
                'category_id' => 5,
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subWeeks(2)
            ],
            [
                'title' => 'Biologi untuk SMA/MA Kelas XII',
                'subject' => 'Biologi',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-924-7',
                'description' => 'Buku paket Biologi untuk siswa kelas XII SMA/MA. Membahas bioteknologi, ekologi, dan lingkungan.',
                'published_date' => '2024-03-01',
                'pages' => 290,
                'language' => 'Indonesian',
                'stock' => 39,
                'price' => 86000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 6,
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subMonths(1)
            ],
            [
                'title' => 'Geografi untuk SMA/MA Kelas XII',
                'subject' => 'Geografi',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-925-4',
                'description' => 'Buku paket Geografi untuk siswa kelas XII SMA/MA. Membahas interaksi keruangan, pembangunan berkelanjutan, dan mitigasi bencana.',
                'published_date' => '2024-03-01',
                'pages' => 250,
                'language' => 'Indonesian',
                'stock' => 36,
                'price' => 78000,
                'condition' => 'baik',
                'damaged_count' => 2,
                'damage_notes' => 'Cover sobek 2 buku',
                'category_id' => 8,
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subWeeks(1)
            ],
            [
                'title' => 'Sosiologi untuk SMA/MA Kelas XII',
                'subject' => 'Sosiologi',
                'grade_level' => 'XII',
                'semester' => null,
                'curriculum_type' => 'Kurikulum Merdeka',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Kemendikbud',
                'published_year' => 2024,
                'curriculum_year' => 2022,
                'isbn' => '978-602-427-926-1',
                'description' => 'Buku paket Sosiologi untuk siswa kelas XII SMA/MA. Membahas perubahan sosial, globalisasi, dan modernisasi.',
                'published_date' => '2024-03-01',
                'pages' => 230,
                'language' => 'Indonesian',
                'stock' => 34,
                'price' => 76000,
                'condition' => 'baik',
                'damaged_count' => 0,
                'damage_notes' => null,
                'category_id' => 10,
                'created_at' => Carbon::now()->subWeeks(3),
                'updated_at' => Carbon::now()->subWeeks(3)
            ],

            // Kurikulum 2013 - Beberapa buku lama
            [
                'title' => 'Matematika SMA/MA Kelas X - K13',
                'subject' => 'Matematika',
                'grade_level' => 'X',
                'semester' => null,
                'curriculum_type' => 'Kurikulum 2013',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Erlangga',
                'published_year' => 2017,
                'curriculum_year' => 2013,
                'isbn' => '978-602-298-100-5',
                'description' => 'Buku paket Matematika Kurikulum 2013 untuk kelas X SMA/MA.',
                'published_date' => '2017-06-01',
                'pages' => 300,
                'language' => 'Indonesian',
                'stock' => 25,
                'price' => 65000,
                'condition' => 'rusak',
                'damaged_count' => 8,
                'damage_notes' => 'Buku lama, banyak yang rusak dan usang',
                'category_id' => 1,
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subMonths(6)
            ],
            [
                'title' => 'Bahasa Indonesia SMA/MA Kelas XI - K13',
                'subject' => 'Bahasa Indonesia',
                'grade_level' => 'XI',
                'semester' => null,
                'curriculum_type' => 'Kurikulum 2013',
                'book_type' => 'Buku Siswa',
                'publisher' => 'Erlangga',
                'published_year' => 2017,
                'curriculum_year' => 2013,
                'isbn' => '978-602-298-101-2',
                'description' => 'Buku paket Bahasa Indonesia Kurikulum 2013 untuk kelas XI SMA/MA.',
                'published_date' => '2017-06-01',
                'pages' => 280,
                'language' => 'Indonesian',
                'stock' => 20,
                'price' => 62000,
                'condition' => 'rusak',
                'damaged_count' => 10,
                'damage_notes' => 'Kondisi sangat buruk, perlu penggantian',
                'category_id' => 2,
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subMonths(4)
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
